version: "3.9"
services:
  web:
    image: nginxnsomadhan:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./ctemplates:/etc/nginx/sites-available:rw
      - ./templates:/etc/nginx/templates:rw
      - ./server1:/var/www/server1.example.com:rw
      - ./server3:/var/www/server3.com.bd:rw
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - env_name=hellow
      - domain_name1=server3
